### PR TITLE
BC-196 - fix "server manifest not found" on start on build 

### PR DESCRIPTION
**Pull request by virgilchiriac**
# Description
fix "server manifest not found" on start on build 

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-196
https://ticketsystem.hpi-schul-cloud.org/browse/BC-68

https://github.com/hpi-schul-cloud/schulcloud-server/pull/3000
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2670
https://github.com/hpi-schul-cloud/nuxt-client/pull/1904

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.hpi-schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Review by Loki-Afro — CHANGES_REQUESTED** [review]
why not solve the solve of the issue?
e2e tests are currently running after there is a docker image created, you should just need to wait for it to be done - for example using timeout.

Producing the "same" image twice is not the right way to go.

**Comment by Loki-Afro** [comment]
Another way of implementing this would be very similar to the "dispatch" logic, meaning they will always run AFTER that build_and_push job is done

**Comment by virgilchiriac** [comment]
moving the e2e on push and after image build, should take care of that (https://github.com/hpi-schul-cloud/schulcloud-server/pull/3000)
however, waiting for each of the apps to load, what we do here, is in any case a good idea

**Comment by virgilchiriac** [comment]
> why not solve the solve of the issue?
> e2e tests are currently running after there is a docker image created, you should just need to wait for it to be done - for example using timeout.
> 
> Producing the "same" image twice is not the right way to go.

this was done by adding the e2e in the same job with the build, making it dependent to it

**Comment by Loki-Afro** [comment]
based on virgils commont this pr can be closed without merging.

**Pull request closed without merging**
